liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360, 230]
                    mode: outbound
        logo:
            quality: 75
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: inset
